#!c:\users\shrut\documents\github\biolinkml\pyenv\scripts\python.exe

import os
import sys

if __name__ == "__main__":
    sys.path.append(os.path.join(os.path.join(os.getcwd(), os.path.dirname(__file__)), '..'))
    from pyjsg.parser_impl.generate_python import generate
    generate(sys.argv[1:])
